### ISSUE TITLE
Long model loading time

### ISSUE THREAD

**Issue by williamljb** [isantesteban/vto-garment-collisions#1]
Hi Igor,

Can you inform me of how long it takes for the load_model() function to complete? It takes over 15 minutes in my case and I am not sure if there is anything I missed.

Thanks!

**Comment by williamljb** [comment]
I waited for 4 hours and it still didn't come up. I removed 'tshirt/gru' and 'tshirt/decoder' to bypass the two large networks. Now I have a second problem:
It complains about `Layer model expects 2 input(s), but it received 1 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, 3) dtype=float32>]` [here](https://github.com/isantesteban/vto-garment-collisions/blob/main/src/model.py#L108). Can you double-check the model is actually running?

**Comment by isantesteban** [comment]
Hi! The model should load in a few seconds. We've tested this code in TensorFlow 2.2.1 and it runs without errors, can you tell me which version of the library are you using?

**Comment by williamljb** [comment]
Python 3.7.10, numpy 1.18.5, scipy 1.6.0, chumpy 0.70, tensorflow 2.4.2

I suspect it is because tensorflow updated some of the tf.keras code but I am not sure. I will roll back to 2.2.1 and see if it runs.

Thanks!

**Comment by dancasas** [comment]
Try setting up an Anaconda environment like this, it should work: `conda create -n santesteban19 python tensorflow=2.2 numpy=1.18 scipy=1.7.1
`

**Comment by williamljb** [comment]
It works. Thanks for the help!
