### ISSUE TITLE
blender images get wrong direction

### ISSUE THREAD

**Issue by skeras** [isantesteban/vto-garment-collisions#5]
Hi Igor,
    Thanks for your great project.
     when I run comand "blender --background rendering/scene.blend --python rendering/render.py --path results/tshirt/07_02", get wrong image direction, can you help me?
![00000](https://user-images.githubusercontent.com/29603361/161903456-3034ceb3-4a0d-44f8-a9bc-e23931a13d4d.jpg)

**Comment by isantesteban** [comment]
Hi, I've tried to reproduce your problem but my renders are in the correct direction so I don't know what is the issue
![00000](https://user-images.githubusercontent.com/17111347/163971410-ebdbc15f-5824-4384-97ac-b9e0b80880e3.jpg)

I'm using blender-2.93, could you check if your version is the same?

**Comment by skeras** [comment]
Hi,
   Thank you very much for your reply,  I'm using blender-2.93 too.
   other info:
         Ubuntu18.04
         Python3.8
    I clone this project again and run commad again same problem.
    I use blender open scene.blend file, then import model generate obj file, the blender display is not right, so i think scene.blend direction should be changed, I'm right?
![1](https://user-images.githubusercontent.com/29603361/164038908-96306250-49a0-4806-a3b2-6c11c66c8414.png)
![2](https://user-images.githubusercontent.com/29603361/164038934-b55058b6-61a2-499b-ae97-bcfb8cd1219a.png)

**Comment by isantesteban** [comment]
I've tried to reproduce the issue but when I open scene.blend and load the objects the direction seems to be ok

![image](https://user-images.githubusercontent.com/17111347/164252030-2244de96-1112-4c27-9c9d-f924ee3cbd1a.png)

I have no idea why it's not working for you, sorry

**Comment by skeras** [comment]
Thanks a lot, I found this is blender's problem (at ubuntu18.04), I copyed the file to windows works OK.
